name: novaexpress
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_widget_from_html: ^0.17.1

  # State Management
  flutter_riverpod: ^2.5.1

  # Network
  dio: ^5.4.2
  http: ^1.2.1

  # Local storage / cache
  shared_preferences: ^2.5.4
  easy_cache_manager: ^0.1.8

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^14.0.1

  # JSON / Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  image_picker: ^1.2.1
  firebase_app_check: ^0.4.1+3
  video_player: ^2.8.1
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.8
  freezed: ^2.5.2
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/news_header.jpg
    - assets/images/logo.png
    - assets/videos/onboarding_bg.mp4
